Repository sleiderr/fzkernel, pull requests merged in 2023-08, with the labels that each got.

#16 feat(vesa): implement VESA support
  Cargo.lock
  src/bios/f-init/Cargo.toml
  src/bios/f-init/f-init.ld
  src/bios/f-init/src/main.rs
  src/bios/f-init/x86_64-fbios.json
  src/bios/f-init32/Cargo.lock
  src/bios/f-init32/Cargo.toml
  src/bios/f-init32/f-init32.ld
  src/bios/f-init32/x86_64-fbios.json
  src/bios/f-initmbr/x86_64-fbios.json
  src/bios/flib/Cargo.toml
  src/bios/flib/src/lib.rs
  src/bios/flib/src/video_io/mod.rs
  src/bios/flib/src/video_io/vesa/mod.rs
  src/bios/flib/src/video_io/vesa/video_mode.rs
Labels: enhancement

#21 feat(framebuffer): implement a text-based framebuffer
  Cargo.lock
  src/bios/f-init/src/main.rs
  src/bios/f-init32/Cargo.toml
  src/bios/f-init32/f-init32.ld
  src/bios/f-init32/src/arch/x86/setup.S
  src/bios/f-init32/src/main.rs
  src/bios/f-init32/x86_64-fbios.json
  src/bios/f-initmbr/src/main.rs
  src/bios/flib/Cargo.toml
  src/bios/flib/src/mem/e820.rs
  src/bios/flib/src/video_io/vesa/framebuffer.rs
  src/bios/flib/src/video_io/vesa/mod.rs
  src/bios/flib/src/video_io/vesa/video_mode.rs
Labels: enhancement, graphic

#22 feat(text-macros): general purpose text macros for formatting / output
  src/bios/f-init/f-init.ld
  src/bios/f-init/src/main.rs
  src/bios/f-init/src/pswitch/gdt.rs
  src/bios/f-init32/f-init32.ld
  src/bios/f-init32/src/main.rs
  src/bios/f-initmbr/Cargo.toml
  src/bios/flib/src/bios/smbios.rs
  src/bios/flib/src/lib.rs
  src/bios/flib/src/mem/e820.rs
  src/bios/flib/src/video_io/io.rs
  src/bios/flib/src/video_io/vesa/framebuffer.rs
  src/bios/flib/src/video_io/vesa/macros.rs
  src/bios/flib/src/video_io/vesa/mod.rs
  src/bios/flib/src/video_io/vesa/video_mode.rs
Labels: enhancement, graphic

#23 feat(graphic): implement a background color for `TextFrameBuffer`
  src/bios/flib/src/video_io/vesa/framebuffer.rs
  src/bios/flib/src/video_io/vesa/video_mode.rs
Labels: enhancement, graphic

#24 feat(bss): zeroise the bss section on program entry
  Cargo.lock
  src/bios/f-init/src/main.rs
  src/bios/f-init32/f-init32.ld
  src/bios/f-init32/src/main.rs
  src/bios/flib/src/mem/mod.rs
Labels: fix

#26 refactor: improve flib file structure
  .idea/frozenboot.iml
  src/bios/f-init/src/main.rs
  src/bios/f-init/src/pswitch/a20.rs
  src/bios/f-init/src/pswitch/gdt.rs
  src/bios/f-init32/src/main.rs
  src/bios/f-initmbr/src/main.rs
  src/bios/flib/src/bios/smbios.rs
  src/bios/flib/src/disk_io/mod.rs
  src/bios/flib/src/fs/mod.rs
  src/bios/flib/src/fs/partitions/mbr.rs
  src/bios/flib/src/fs/partitions/mod.rs
  src/bios/flib/src/gdt/mod.rs
  src/bios/flib/src/io/disk/bios.rs
  src/bios/flib/src/io/disk/mod.rs
  src/bios/flib/src/io/mod.rs
  src/bios/flib/src/io/ps2/mod.rs
  src/bios/flib/src/lib.rs
  src/bios/flib/src/mem/e820.rs
  src/bios/flib/src/mem/gdt/mod.rs
  src/bios/flib/src/mem/mod.rs
  src/bios/flib/src/part_mbr/mod.rs
  src/bios/flib/src/ps2/mod.rs
  src/bios/flib/src/video/io.rs
  src/bios/flib/src/video/mod.rs
  src/bios/flib/src/video/vesa/framebuffer.rs
  src/bios/flib/src/video/vesa/macros.rs
  src/bios/flib/src/video/vesa/mod.rs
  src/bios/flib/src/video/vesa/video_mode.rs
  src/bios/flib/src/x86/interrupts.rs
  src/bios/flib/src/x86/mod.rs
Labels: refactor

#28 feat(rtc-time): implements a DateTime abstraction, and RTC related utilities to retrieve the current UTC time
  src/bios/f-init/src/pswitch/a20.rs
  src/bios/f-init32/src/main.rs
  src/bios/flib/src/io/io.rs
  src/bios/flib/src/io/mod.rs
  src/bios/flib/src/lib.rs
  src/bios/flib/src/time/mod.rs
  src/bios/flib/src/time/rtc.rs
  src/bios/flib/src/video/vesa/macros.rs
  src/bios/flib/src/x86/interrupts.rs
Labels: enhancement

#31 feat(acpi): basic ACPI implementation
  src/bios/flib/src/io/acpi/mod.rs
  src/bios/flib/src/io/acpi/sdt.rs
  src/bios/flib/src/io/mod.rs
Labels: enhancement

#20 feat: Implement Interrupt Descriptor Table and Interrupt Routines
  src/bios/f-init/src/pswitch/a20.rs
  src/bios/f-init/src/pswitch/gdt.rs
  src/bios/f-init32/Cargo.toml
  src/bios/f-init32/f-init32.ld
  src/bios/f-init32/src/interrupts/handlers.rs
  src/bios/f-init32/src/interrupts/mod.rs
  src/bios/f-init32/src/main.rs
  src/bios/f-initmbr/src/main.rs
  src/bios/f-macros/Cargo.toml
  src/bios/f-macros/src/lib.rs
  src/bios/flib/Cargo.toml
  src/bios/flib/src/idt/idt.rs
  src/bios/flib/src/idt/mod.rs
  src/bios/flib/src/int/mod.rs
  src/bios/flib/src/int/scheduler.rs
  src/bios/flib/src/io/mod.rs
  src/bios/flib/src/io/pic/mod.rs
  src/bios/flib/src/lib.rs
  src/bios/flib/src/time/rtc.rs
  src/bios/flib/src/x86/mod.rs
Labels: enhancement

#36 fix(bmalloc): fixed never re-allocated sections when block-merging
  src/bios/flib/src/mem/bmalloc/heap.rs
Labels: fix

#37 fix(bmalloc): invalid buddy size calculation, full heap was never freed
  src/bios/flib/src/mem/bmalloc/heap.rs
Labels: fix

#33 feat(hpet): HPET init/access/control implementation
  src/bios/f-init32/src/main.rs
  src/bios/flib/src/io/acpi/hpet.rs
  src/bios/flib/src/io/acpi/mod.rs
Labels: enhancement

#38 feat(cpuid/msr): add `CPUID` and `MSR` utils to interact with the CPU
  src/bios/flib/src/x86/cpuid.rs
  src/bios/flib/src/x86/mod.rs
  src/bios/flib/src/x86/msr.rs
Labels: enhancement

#34 feat(tsc): implement TSC related stuff: setup, read, calibrate, ...
  Cargo.lock
  src/bios/f-init32/src/main.rs
  src/bios/flib/src/x86/cpuid.rs
  src/bios/flib/src/x86/mod.rs
  src/bios/flib/src/x86/tsc.rs
Labels: enhancement

#42 chore: manifest update
  Cargo.toml
  build/Cargo.toml
  build/build.rs
  build/src/main.rs
  src/fzboot/main/Cargo.toml
  src/fzboot/mbr/Cargo.toml
  src/fzboot/proc_macros/Cargo.toml
  src/fzboot/real/Cargo.toml
Labels: r-documentation, t-minor

#46 fix(acpi): sdt_getter returns pointer to the SDT instead of a copy of it
  src/io/acpi/hpet.rs
  src/io/acpi/sdt.rs
Labels: fix, refactor, t-urgent
