Repository sleiderr/fzkernel, pull requests merged in 2024-01, with the labels that each got.

#43 Implements `APIC` and `IoAPIC`s support
  Cargo.toml
  build/Cargo.lock
  src/deps/pod-enum/.gitignore
  src/deps/pod-enum/Cargo.toml
  src/deps/pod-enum/README.md
  src/deps/pod-enum/macros/Cargo.toml
  src/deps/pod-enum/macros/src/lib.rs
  src/deps/pod-enum/src/lib.rs
  src/deps/pod-enum/tests/basic.rs
  src/fzboot/irq/handlers.rs
  src/fzboot/irq/mod.rs
  src/fzboot/main/src/main.rs
  src/fzboot/proc_macros/src/lib.rs
  src/fzboot/real/src/pswitch/a20.rs
  src/fzboot/time/rtc.rs
  src/io/mod.rs
  src/io/pic/mod.rs
  src/io/ps2/mod.rs
  src/mem/mod.rs
  src/x86/apic/io_apic.rs
  src/x86/apic/local_apic.rs
  src/x86/apic/mod.rs
  src/x86/apic/mp_table.rs
  src/x86/mod.rs
  src/x86/msr.rs
Labels: enhancement, r-hardware, r-arch, t-urgent

#67 feat(x86): rewrite real mode code in plain assembly
  .gitignore
  build/Cargo.lock
  build/Cargo.toml
  build/build.rs
  build/src/components/build.rs
  build/src/main.rs
  src/fzboot/irq/mod.rs
  src/fzboot/main/f-init32.ld
  src/fzboot/main/src/arch/x86/setup.S
  src/fzboot/main/src/main.rs
  src/fzboot/mbr/.cargo/config.toml
  src/fzboot/mbr/Cargo.lock
  src/fzboot/mbr/Cargo.toml
  src/fzboot/mbr/src/main.rs
  src/fzboot/mbr/x86_64-fbios.json
  src/fzboot/real/Cargo.lock
  src/fzboot/real/Cargo.toml
  src/fzboot/real/f-init.ld
  src/fzboot/real/src/main.rs
  src/fzboot/real/src/pswitch/a20.rs
  src/fzboot/real/src/pswitch/gdt.rs
  src/fzboot/real/src/pswitch/mod.rs
  src/fzboot/real/x86_64-fbios.json
  src/mem/e820.rs
  src/video/vesa/mod.rs
  src/video/vesa/video_mode.rs
  src/x86/real/Makefile
  src/x86/real/a20.S
  src/x86/real/boot.S
  src/x86/real/boot.ld
  src/x86/real/mem.S
  src/x86/real/real.S
  src/x86/real/real.ld
  src/x86/real/vesa.S
Labels: r-hardware, r-arch, r-boot, r-build, t-urgent

#68 feat(x86-cr): `ControlRegister` implementations (CR0, CR3, CR4)
  src/fzboot/err.rs
  src/lib.rs
  src/mem/mod.rs
  src/x86/mod.rs
  src/x86/registers/control.rs
  src/x86/registers/mod.rs
Labels: enhancement, r-arch, t-urgent

#69 feat(x86-paging): 64-bit paging structures and initialization
  src/fzboot/main/src/main.rs
  src/lib.rs
  src/mem/bmalloc/heap.rs
  src/mem/mod.rs
  src/x86/mod.rs
  src/x86/msr.rs
  src/x86/paging/mod.rs
  src/x86/paging/page_table/mod.rs
  src/x86/paging/page_table/translate.rs
Labels: enhancement, r-arch, t-urgent

#71 feat(kernel): initialize kernel code, implement it in the build process
  .gitignore
  build/Cargo.lock
  build/Cargo.toml
  build/src/cli/app.rs
  build/src/components/build.rs
  build/src/main.rs
  build/src/ui/build/mod.rs
  src/fzboot/kernel/Cargo.toml
  src/fzboot/kernel/kernel.ld
  src/fzboot/kernel/src/main.rs
  src/fzboot/kernel/x86_64-fbios.json
  src/x86/real/Makefile
  src/x86/real/boot.S
Labels: enhancement, r-build, t-urgent
